# Použij oficiální PHP image s Apachem
FROM php:8.0-apache

# Zkopíruj všechny soubory do defaultní složky pro web server
COPY . /var/www/html/

# Exponuj port 80 pro přístup k webové stránce
EXPOSE 80
